version: "3"
services:
  db:
    image: mysql:8
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    env_file:
      - docker.env
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - "3306:3306"
    expose:
      # Opens port 3306 on the container
      - "3306"
      # Where our data will be persisted
    volumes:
      - ./database/my.cnf:/etc/mysql/conf.d/my.cnf

      - my-db:/var/lib/mysql
# Names our volume
volumes:
  my-db:
